### ISSUE TITLE
Добавить README.md и бейджики

### ISSUE THREAD

**Issue by coursar** [artem-eremchuk/calculator-bonus#1]

**Comment by artem-eremchuk** [comment]
Работу еще не доделал, пока практикуюсь с git (тема трудная для понимая, лично для меня)

**Comment by artem-eremchuk** [comment]
@coursar, у меня проблема с Travis CI 
Он не разворачивается полностью, горит красным ошибка

**Comment by coursar** [comment]
Бейджик в README.md поставьте - разберёмся

**Comment by coursar** [comment]
вы просто неправильно прописали файл .travis.yml

**Comment by coursar** [comment]
сделайте `git pull` в консоли
