### ISSUE TITLE
Вы всё-таки считаете бонусы, а не продажи, поэтому разумно назвать calculateBonus

### ISSUE THREAD

**Issue by coursar** [artem-eremchuk/calculator-bonus#3]
https://github.com/artem-eremchuk/calculator-bonus/blob/3b1b5cd910f02d1b5185c63a353d48d050e178d3/src/js/app.js#L4

**Comment by artem-eremchuk** [comment]
@coursar, переименовал 
https://github.com/artem-eremchuk/calculator-bonus/blob/6e0f1fe6e5a5f0494b37b79f578da7667c09c9b3/src/js/app.js#L4

**Comment by coursar** [comment]
если сделали, то закрывайте issue
