### ISSUE TITLE
Этот кусок кода не нужен, смысл прибавлять 0?

### ISSUE THREAD

**Issue by coursar** [artem-eremchuk/calculator-bonus#4]
https://github.com/artem-eremchuk/calculator-bonus/blob/3b1b5cd910f02d1b5185c63a353d48d050e178d3/src/js/lib.js#L5-L7

**Comment by artem-eremchuk** [comment]
@coursar, удалил
https://github.com/artem-eremchuk/calculator-bonus/blob/6e0f1fe6e5a5f0494b37b79f578da7667c09c9b3/src/js/lib.js#L1-L11
